<a href="https://colab.research.google.com/github/payaljain2003/python/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [6]:
df = df.drop(['id','Unnamed: 32'], axis = 1)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [32]:
X_train,X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [33]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
X_train

array([[-0.53817592, -0.2975309 , -0.55614717, ..., -0.39626084,
         0.51520651, -0.49992189],
       [ 1.16458691, -0.09577392,  1.0997106 , ...,  0.95429494,
        -0.13679145, -0.10722655],
       [-0.31435186,  0.60444148, -0.17938726, ...,  1.38376291,
         2.37805781,  1.25318229],
       ...,
       [-0.09619422,  0.71600122, -0.0510675 , ...,  0.79853719,
         0.29359144,  0.50501137],
       [ 1.87572413,  2.8119002 ,  1.79665494, ...,  0.77736624,
        -0.0468607 , -0.09643822],
       [-0.52684306, -0.31651979, -0.55778704, ..., -0.48971549,
         0.34658634, -0.14282805]])

In [35]:
y_train

367    B
317    M
8      M
220    B
293    B
      ..
505    B
304    B
196    M
265    M
155    B
Name: diagnosis, Length: 455, dtype: object

In [36]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [37]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,

In [38]:
X_test

array([[-0.16985784, -0.0910267 , -0.15478922, ...,  0.46585074,
        -0.37125377, -0.38340788],
       [ 0.60644335,  0.05613722,  0.73483974, ...,  0.95278273,
         0.67579713,  0.39874629],
       [ 0.94926249,  4.7487672 ,  0.88242795, ...,  1.39283618,
        -0.07094929,  0.05351962],
       ...,
       [ 0.3316214 ,  0.74448456,  0.28879536, ...,  0.12257881,
         0.44615253,  0.74181529],
       [-1.10765234, -0.42570592, -1.09976376, ..., -1.19138147,
        -0.0468607 , -0.31705963],
       [-0.25485432,  2.08557507, -0.28679868, ..., -0.52797443,
        -0.68119369, -1.05390281]])

In [39]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [40]:
X_train_tensor

tensor([[-0.5382, -0.2975, -0.5561,  ..., -0.3963,  0.5152, -0.4999],
        [ 1.1646, -0.0958,  1.0997,  ...,  0.9543, -0.1368, -0.1072],
        [-0.3144,  0.6044, -0.1794,  ...,  1.3838,  2.3781,  1.2532],
        ...,
        [-0.0962,  0.7160, -0.0511,  ...,  0.7985,  0.2936,  0.5050],
        [ 1.8757,  2.8119,  1.7967,  ...,  0.7774, -0.0469, -0.0964],
        [-0.5268, -0.3165, -0.5578,  ..., -0.4897,  0.3466, -0.1428]],
       dtype=torch.float64)

In [42]:
X_train_tensor.shape

torch.Size([455, 30])

In [41]:
y_train_tensor.shape

torch.Size([455])

In [59]:
class MySimpleNeuralNetwork():
  def __init__(self, X):
    self.weights = torch.rand(X_train_tensor.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def fowards(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred =  torch.sigmoid(z)
    return y_pred

  def loss(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [63]:
learning_rate = 0.1
epochs = 25

In [60]:
#create_model

model = MySimpleNeuralNetwork(X_train_tensor)
model.weights

tensor([[0.5350],
        [0.6792],
        [0.9001],
        [0.3752],
        [0.1548],
        [0.3061],
        [0.4442],
        [0.6492],
        [0.4352],
        [0.8099],
        [0.0753],
        [0.5457],
        [0.2498],
        [0.9398],
        [0.9418],
        [0.9655],
        [0.3758],
        [0.6640],
        [0.8078],
        [0.9049],
        [0.9612],
        [0.9123],
        [0.9057],
        [0.4990],
        [0.5599],
        [0.4262],
        [0.4139],
        [0.1912],
        [0.7869],
        [0.6735]], dtype=torch.float64, requires_grad=True)

In [50]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [64]:

for epoch in range(epochs):
  # forward pass
  y_pred = model.fowards(X_train_tensor)
  #print(y_pred.shape)

  #calculate loss
  loss = model.loss(y_pred, y_train_tensor)
  print(f'Epoch: {epoch+1}, loss : {loss.item()}')

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, loss : {loss.item()}')


Epoch: 1, loss : 4.03642788901264
Epoch: 1, loss : 4.03642788901264
Epoch: 2, loss : 3.9292213194191663
Epoch: 2, loss : 3.9292213194191663
Epoch: 3, loss : 3.8185100230487254
Epoch: 3, loss : 3.8185100230487254
Epoch: 4, loss : 3.7028768847596063
Epoch: 4, loss : 3.7028768847596063
Epoch: 5, loss : 3.5861237251483704
Epoch: 5, loss : 3.5861237251483704
Epoch: 6, loss : 3.4630198714638896
Epoch: 6, loss : 3.4630198714638896
Epoch: 7, loss : 3.3311046726716955
Epoch: 7, loss : 3.3311046726716955
Epoch: 8, loss : 3.1948856127091023
Epoch: 8, loss : 3.1948856127091023
Epoch: 9, loss : 3.0548759396652554
Epoch: 9, loss : 3.0548759396652554
Epoch: 10, loss : 2.911600120562974
Epoch: 10, loss : 2.911600120562974
Epoch: 11, loss : 2.7639282708969724
Epoch: 11, loss : 2.7639282708969724
Epoch: 12, loss : 2.6126921948587856
Epoch: 12, loss : 2.6126921948587856
Epoch: 13, loss : 2.462562679955858
Epoch: 13, loss : 2.462562679955858
Epoch: 14, loss : 2.3143099300651913
Epoch: 14, loss : 2.3143099

In [68]:
model.weights

tensor([[ 0.0680],
        [ 0.2563],
        [ 0.4076],
        [-0.0902],
        [-0.2803],
        [-0.3477],
        [-0.2268],
        [-0.0055],
        [-0.0036],
        [ 0.4631],
        [-0.4114],
        [ 0.3108],
        [-0.2350],
        [ 0.5267],
        [ 0.6709],
        [ 0.4048],
        [-0.1427],
        [ 0.0875],
        [ 0.5745],
        [ 0.4005],
        [ 0.4414],
        [ 0.4874],
        [ 0.3659],
        [-0.0057],
        [ 0.1099],
        [-0.1595],
        [-0.2002],
        [-0.4538],
        [ 0.4050],
        [ 0.1784]], dtype=torch.float64, requires_grad=True)

In [69]:
model.bias

tensor([-0.1152], dtype=torch.float64, requires_grad=True)

In [78]:
with torch.no_grad():
  y_pred = model.fowards(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

#print(y_pred)

Accuracy: 0.5200061798095703
